### DISCUSSION TITLE
使用docker-compose 部署后，网页页面404

### DISCUSSION THREAD

**Discussion by OcrSu** [xfgryujk/blivechat#198] [提问] [answered]
![image](https://github.com/xfgryujk/blivechat/assets/75876201/67b6235b-5fa0-4e79-a452-6407dd60bb89)
![image](https://github.com/xfgryujk/blivechat/assets/75876201/434e588b-a9cc-488f-b4fd-335c4babe78c)

这里是部署配置

```
services:
  blivechat:
    image: xfgryujk/blivechat:v1.9.1
    container_name: blivechat
    network_mode: "host"
    volumes:
      # custom configurations
      - ./config:/mnt/data/data
      - ./config:/mnt/data/
    restart: unless-stopped
```

**Comment by xfgryujk** [comment]
data目录没初始化，run的时候让docker自动创建卷，会初始化

**Reply by OcrSu** [reply]
正在研究中
```
volumes:
      # custom configurations
      - ./config:/mnt/data/data
      - ./config:/mnt/data/
```


这个不是data目录的卷创建吗？

![image](https://github.com/xfgryujk/blivechat/assets/75876201/66de507f-2076-43e0-9aa5-de6bf5c7dd76)

这里程序自己建立了一个数据库

**Reply by xfgryujk** [reply]
我没用过docker-compose，但我觉得这么写只是把本地目录挂载到容器了，不是创建新的卷

**Reply by 0xAmad3us** [reply]
卷名不一样导致的，下面这个是可用的
```
services:
  blivechat:
    image: xfgryujk/blivechat:latest
    ports:
      - 12450:12450
    volumes:
      - data:/mnt/data
volumes:
  data:
```

或者
```
services:
  ......
    volumes:
      - <volname>:/mnt/data
volumes:
  <volname>:
    name: blivechat-data
```

自动生成的卷卷名需为"blivechat-data"
