### DISCUSSION TITLE
[feature request] support for docker  arm64 version

### DISCUSSION THREAD

**Discussion by jqtmviyu** [xfgryujk/blivechat#211] [想法]
请求为arm64提供docker支持

**Comment by xfgryujk** [comment]
但是我拒绝，我最喜欢的事就是对伸手党说NO

**Comment by jqtmviyu** [comment]
没必要这么冲. 

## 有arm设备的可以使用: 

```yaml
services:
    blivechat:
        image: 'jqtmviyu/blivechat-arm64:latest'
        container_name: blivechat
        ports:
            - '12450:12450'
        volumes:
          - ./data:/root/blivechat/data
        restart: unless-stopped
```

## 提点建议:

1.  如果不先源码运行, blivechat.log 和 mysql 初始文件 不会自动生成, 不清楚是不是权限的问题.
2. 使用alpine作为底, 可以大大缩小镜像体积, 300M==>90M
3. npm 也被墙了, 同样可以加淘宝源参数

参考:

```dockerfile
#
# 构建前端
#
FROM node:18.17.0-alpine AS builder
ARG BASE_PATH='/root/blivechat'
WORKDIR "${BASE_PATH}/frontend"

# 前端依赖
COPY frontend/package.json ./
RUN npm install --registry=https://registry.npmmirror.com

# 编译前端
COPY frontend ./
RUN npm run build

#
# 准备后端
#
FROM python:3.8.12-alpine
ARG BASE_PATH='/root/blivechat'
WORKDIR "${BASE_PATH}"

# 安装依赖工具和运行时必备工具
RUN apk add --no-cache --virtual .build-deps \
        build-base \
        libffi-dev \
        openssl-dev \
    && apk add --no-cache \
        bash

# 安装 Python 依赖
COPY blivedm/requirements.txt blivedm/
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt

# 复制应用程序代码和配置
COPY . ./
RUN rm -rf frontend/*

# 复制编译好的前端文件
COPY --from=builder "${BASE_PATH}/frontend/dist" "${BASE_PATH}/frontend/dist/"

# 清理构建依赖
RUN apk del .build-deps

# 设置运行时配置
VOLUME ["${BASE_PATH}/data", "${BASE_PATH}/log"]
EXPOSE 12450
ENTRYPOINT ["python3", "main.py"]
CMD ["--host", "0.0.0.0", "--port", "12450"]

```
