### ISSUE TITLE
使用docker-compose 部署后，网页页面404

### ISSUE THREAD

**Issue by OcrSu** [xfgryujk/blivechat#196]
![image](https://github.com/xfgryujk/blivechat/assets/75876201/67b6235b-5fa0-4e79-a452-6407dd60bb89)
![image](https://github.com/xfgryujk/blivechat/assets/75876201/434e588b-a9cc-488f-b4fd-335c4babe78c)

这里是部署配置

```
services:
  blivechat:
    image: xfgryujk/blivechat:v1.9.1
    container_name: blivechat
    network_mode: "host"
    volumes:
      # custom configurations
      - ./config:/mnt/data/data
      - ./config:/mnt/data/
    restart: unless-stopped
```
